"""Remove partner id column

Revision ID: 5dea988a0349
Revises: de2de58b18bc
Create Date: 2020-10-28 17:20:12.296241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dea988a0349'
down_revision = 'de2de58b18bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'partner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # no turning back
    pass
    # ### end Alembic commands ###
