"""Add example column

Revision ID: 7f85321361bf
Revises: b1bc752b6189
Create Date: 2020-04-07 17:25:36.078547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f85321361bf'
down_revision = 'b1bc752b6189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('example_composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
    # TODO nullable true

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'example_composition')
    # ### end Alembic commands ###
