"""Create primary key

Revision ID: b08bee53dee3
Revises: 5dea988a0349
Create Date: 2020-10-30 12:19:48.260962

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b08bee53dee3'
down_revision = '5dea988a0349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
        "template_pkey", "template",
        ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('template_pkey', 'template', type_='primary')
    # ### end Alembic commands ###
