"""TagColumn

Revision ID: b1bc752b6189
Revises: f841a0bf1c4c
Create Date: 2020-02-24 18:31:07.358965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bc752b6189'
down_revision = 'f841a0bf1c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'tags')
    # ### end Alembic commands ###
