"""Add example column

Revision ID: de2de58b18bc
Revises: b1bc752b6189
Create Date: 2020-04-08 18:36:27.381025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2de58b18bc'
down_revision = 'b1bc752b6189'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('template', sa.Column('example_composition', postgresql.JSONB(astext_type=sa.Text()),
                                        nullable=False, server_default="{}"))
    op.alter_column('template', 'example_composition',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'example_composition')
    # ### end Alembic commands ###
